-- MySQL Script generated by MySQL Workbench
-- 05/25/16 13:09:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema melisv2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `melis_hist_page_historic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_hist_page_historic` (
  `hist_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `hist_page_id` INT(11) NOT NULL COMMENT '',
  `hist_action` VARCHAR(45) NOT NULL COMMENT '',
  `hist_date` DATETIME NOT NULL COMMENT '',
  `hist_user_id` INT(11) NOT NULL COMMENT '',
  `hist_description` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`hist_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'Saves the historic actions';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
