<?php

	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
	
?>
<div class="tab-pane" <?= $id; ?>>
	<ul class="list">
		<?php 
			foreach ($this->pages as $page)
			{
				$tagsOpening = 'class="disable-widget-hover"';
				if ($page['page_accessible'])
					$tagsOpening = 'class="melis-openrecenthistoric" data-page-title="' . $page['page_name'] . '"  data-page-icon="' . $page['page_icon'] . '" data-zone-id="' . $page['page_id'] . '_' . $this->pageId . '" data-melis-key="' . $this->pageMelisKey . '" data-page-id="' . $page['page_id'] . '"';
	
				$histActionIcon = '';
				if (!empty($page['hist_action_icon']))
					$histActionIcon = '<span class="' . $page['hist_action_icon'] . '"></span>';
		?>
		<li <?= $tagsOpening; ?>>
			<span ><?= $page['hist_date']; ?> :
				<?= $histActionIcon; ?>
				<span class="ra-username"><?= $page['page_name']; ?> (<?= $page['page_id']; ?>)</span>, 
				<?= $page['hist_action']; ?>,
				<span class="ra-username"><?= $page['hist_user_name']; ?></span>.
			</span>
			<div class="clearfix"></div>
		</li>
		<?php 
			}
		?>				
	</ul>
</div>